// <auto-generated />
namespace Forum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class catimg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catimg));
        
        string IMigrationMetadata.Id
        {
            get { return "201610241217492_cat-img"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
